language: ruby
rvm:
- 2.6.2
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
before_script:
- bundle exec rails db:create --all
- bundle exec rails db:migrate
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: SDHpmHmkFOyEz/52p5M9c6bCDQV+tDcamr0DBw3u1Ltdn04UjR8cChcsLOpv2ids4KqLA5rHUz96xKYNJHMcyqLXrJoBnWMgLcfdp9oJi3jNQH08luVS+0aRopQHvODqw/F7Sr0hHKl8IvHRcfS41erD9DI4na0tX8XH2dANTnbI92jkajpcEdWvJyQNtq4SY5Ei+RMCGnHb94r6KNOAAy59QqKFqw7XYbfpIlWIdWtYNsbdbUcpLwa52BuoT+2+hDn+SsXlB0BqLjDH2khG6ktEDT9paj8ldhfBtvWMOFixbHRf7wqVwLXf0bmdho7BNuLqygeWHK/62ST80WYnZY7oAotFr8jVvLRMQpmwm5zRYmUGJG4vM35xf92wkUlq1XcC+ahKblQoUX4uBTKP0hptRYKjZCo6ml5KSHx4Zt2lzBMoueUMTUG6x6sAJy/7lK0YkxZfjOZfQvZg6JtpAsJLIx5686ykVA/7yjzHNsX3uaNfy8fWyz1eVkxOhcJ1bje6VW3wneZt+KIuUgOgkw73KGAkVgBqRR+nTIzz7ti4jvr9OcMVuTfYyVUz7U0tabXNtPqdvYD93bQ2P8GWUIwAB4xrMhGuMayxJcmcCA6zS52e0y8De/q7V2muYIRqZICkJ/bM0C7DmYVp5Yonc7uFBjpLxfgKdZGeItIhJVA=
  app: sheltered-wave-82854
  on:
    repo: sgraton/freelancer
  run:
  - rails db:migrate
env:
  secure: k7oSO9gOowCIXC+DYUKbT5crb0vxKYPzjvy8yGqLMZOAtD3ugiQJAydY5Kkg4GTRXCREQe9Wii4zCXGm0yTWGohJmMtiZs11ZrR+M5JecKNyQZ7HfSvZirM3WnVoiojuhaqR3VKkQoU//SyopsqHGDGDRSkDLalGlDhfksCh0WWmX6DJ2YECs6GdgizeumxzkbbCVGqWRrvscJ7A97NEafK9ysFHXOEHItOjrAuk7+Lv39iDbGP2CVK5cIbD+/8T/JCBocuQ+i6EHpyRsQEEb259idsSOwByDn27k9oNE3LtR2NgvSCdGdw8jnQsHiKpgRfRWacq4yI0lv7hcmhPzsGaV7fjBIqz6/V3P0GwCtOZg/1Xl3ShOl412GgLm/6x4QZtLyODGleao2f+ExKalUpwVJMeG5ZIDoFGA2FNi15X16iZbLf7SxA+Hsw72B/rB4HATOTtGW3EFjUbil5t+6P5nfBQRrxq/EN6/uXQpatHfswLgeay+7IS2jo/UDPfjxASCEtHvFkBrQhoHyXQPIH7uXzsa/0mnTyjT3J3b9lvtc8WgaRTQob81+DRkeCaCk/KfffYk9DuQiiRFf82naXjtMBy3MH4Md4qJCplYZ5Wk5nDmMj9XKCcb0HJxfRuPmOqRI5Jm7qjco0AThRWgcM15TS1mjLR8MpnCnXGsfE=
