language: ruby
rvm:
- 2.6.3
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
before_script:
- bundle exec rails db:create --all
- bundle exec rails db:migrate
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: BgD3a1hRwUnceYivAIr4EwUo9sXfnfLVC9pocBUelMmeQDlqBPjlb3552ch0Cbj6TzC65qO9k2ClrFGko7HRoYcYAtPy6cZkDyQzVGPUpTuekxakakUGqIajJVet4NMeZGYRjvT5ZT/i1krS5e8Uuv2uYM5PYhoni98r/5eb50s1mzBv6QUgfmvwTEgv3A1oDjwbCUICChMYZpywZvFdmWRQCkcxF6JMhlXRdWkXecJHfPJDPbTUDXptUnjjOUoSvBxjjrSQpr1RPSHVDAcworjxcHgACHoRstQynocQ2riUTEFVT8Bx0JgR5qqxmfoZ5bOLDnX7a5ZSnKqGTP4Vgqm743e9o1aQZZM29hxmr6muq+EkGOmdvNb72Dehwcgexp5UgVLDTphoEARjRwwUe4/XQxnLsuUY9bCzA5ekqdddkN35snycX6umSdw6uG90XMtFjT6kZecvCAJ/48tz7n8AhU6pCHYwvR+trzVktsujk7ZazSrAXoeBCb7oL/Z06Yve/WxIAJGsR1XzCYrB1yYuqbmNuFT6MsCUi1ML0gsXu9n6G/G/7VRRAsvaH+ofI7DhaKccasYKvHiu4ELIvLnT+etm7KL0hPYhc4mvq0s3HQCUnS2mDUgpaFsBazwC4xZQOzj8N2UlFJ/ZV4a7WeaddMFRwpbb8IL0qO+u838=
  app: sheltered-wave-82854
  on:
    repo: sgraton/freelancer
  run:
  - rails db:migrate
env:
  secure: k7oSO9gOowCIXC+DYUKbT5crb0vxKYPzjvy8yGqLMZOAtD3ugiQJAydY5Kkg4GTRXCREQe9Wii4zCXGm0yTWGohJmMtiZs11ZrR+M5JecKNyQZ7HfSvZirM3WnVoiojuhaqR3VKkQoU//SyopsqHGDGDRSkDLalGlDhfksCh0WWmX6DJ2YECs6GdgizeumxzkbbCVGqWRrvscJ7A97NEafK9ysFHXOEHItOjrAuk7+Lv39iDbGP2CVK5cIbD+/8T/JCBocuQ+i6EHpyRsQEEb259idsSOwByDn27k9oNE3LtR2NgvSCdGdw8jnQsHiKpgRfRWacq4yI0lv7hcmhPzsGaV7fjBIqz6/V3P0GwCtOZg/1Xl3ShOl412GgLm/6x4QZtLyODGleao2f+ExKalUpwVJMeG5ZIDoFGA2FNi15X16iZbLf7SxA+Hsw72B/rB4HATOTtGW3EFjUbil5t+6P5nfBQRrxq/EN6/uXQpatHfswLgeay+7IS2jo/UDPfjxASCEtHvFkBrQhoHyXQPIH7uXzsa/0mnTyjT3J3b9lvtc8WgaRTQob81+DRkeCaCk/KfffYk9DuQiiRFf82naXjtMBy3MH4Md4qJCplYZ5Wk5nDmMj9XKCcb0HJxfRuPmOqRI5Jm7qjco0AThRWgcM15TS1mjLR8MpnCnXGsfE=
lang: ruby
script: bundle exec rake